theme: jekyll-theme-merlot
## ¡Bienvenido!
Las donaciones de sangre son más necesarias que nunca durante la actual pandemia por COVID-19. Es por eso que este espacio esta diseñado para las personas que se encuentran en busca de donadores y para todas aquellas personas que quieren y esta en sus posibilidades apoyar.
La finalidad de este proyecto es tener un panel de oportunidades más amplio para la población del estado de **Guanajuato**.

### Dona Sangre, Salva vidas

Las donaciones de sangre que se hacen cada día contribuyen a salvar vidas, algunas de estas son mujeres con complicaciones obstétricas, niños que presenten un cuadro de anemia grave, personas con traumatismo graves o pacientes de intervenciones quirúrgicas y pacientes que requieren transfusiones periódicas por cáncer, operaciones u otros.

Enseguida te compartire algunos puntos interesantes sobre la donación de sangre, esperando que así te animes a la causa.

1. Donando una vez puedes ayudar a tres personas, así es. La sangre puede dividirse en tres productos diferentes, lo cual puede ayudar entre 3 y 4 personas.  

2. La sangre caduca aproximadamente en 45 días, por lo tanto, es necesaria la donación constante de las personas.  

3. Cada 4 minutos, una persona requiere una transfusión sanguínea.  

5. Si donaras 3 veces como mujer y 4 veces como hombre al año de los 18 a los 65 años salvarías más de 500 vidas.  

6. Más del 25% de nosotros necesitará sangre al menos una vez en la vida.  

7. Por cada 10 donadores de sangre, se rechazan 4.   

8. Los donadores de sangre tienen menos riesgo de padecer diabetes y ataques al corazón.  

9. La donación es de 400 ml a 450 ml de sangre, una cantidad que no provoca ningún tipo de cambio en el cuerpo humano.  


### Compatibilidad
<html>
<head><title>Ejemplo de tabla sencilla</title></head>
<body>

<table>
<tr>
  <td><strong>Grupo</strong></td>
  <td><strong>A quien puede donar</strong></td>
  <td><strong>De quien puede recibir</strong></td>
</tr>

<tr>
  <td>A+</td>
  <td>A+ y AB+</td>
  <td> A± y O±</td>
</tr>
<tr>
  <td>A-</td>
  <td> A± y AB±</td>
  <td> A- y O-</td>
</tr>
<tr>
  <td>B+</td>
  <td> B+ y AB+</td>
  <td>B± y O±</td>
</tr>
<tr>
  <td>B-</td>
  <td>B± y AB±</td>
  <td> B- y O-</td>
</tr>

<tr>
  <td>AB+</td>
  <td>AB+</td>
  <td>RECEPTOR UNIVERSAL</td>
</tr>
<tr>
  <td>AB-</td>
  <td>AB±</td>
  <td> A-, B-, AB- y O-</td>
</tr>
<tr>
  <td>O+</td>
  <td> A+, B+, AB+ y O+</td>
  <td> O±</td>
</tr>
<tr>
  <td>O-</td>
  <td>DONANTE UNIVERSAL</td>
  <td>O-</td>
</tr>
</table>

</body>
</html>





### Quiero Donar

Si estas interesado en Donar sangre, plasma o entrar en un proceso de Donación de Organos, deja tu comentario para que pueda llegar a más personas en el mundo y así todos tengamos una oportunidad de seguir viviendo. 

Agrega a tu comentario un correo electronico para que puedan contactarte. 

### Busco Donadores 

Sabemos lo dificil que es buscar donadores y es por eso que ofrecemos este espacio para encontrar una esperanza más. 

Es por esto que se pide que posteen en los comentarios los requisitos necesarios para poder Donar y un correo electronico para que todo interesado pueda contactarse. 


### Comentarios

Si estas interesado en ser Donador o buscar Donadores de sangre, plasma u organos. Escribe en la caja de comentarios para que pueda llegar a más personas. 

   **Recuerda que el mundo es de las personas que se levantan y aportan con sus acciones para hacerlo crecer**. 

<div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://donando-vida.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
